force-app/main/default/objects/Opportunity/fields/WebOrder__c.field-meta.xml
<CustomField>
    <fullName>WebOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Web Order relation for trigger actions</description>
    <label>WebOrder</label>
    <referenceTo>WebOrder__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WebOrderId__c.field-meta.xml
<CustomField>
    <fullName>WebOrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Web Order relation for trigger actions</description>
    <label>WebOrder</label>
    <referenceTo>WebOrder__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WebOrder__c/WebOrder__c.object-meta.xml
<CustomObject>
    <description>WebOrder object store orders and syncrinized with opportunity object</description>
    <label>Web Order</label>
    <nameField>
        <label>WebOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WebOrder__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <description>Close Date Opportunity field</description>
    <label>Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WebOrder__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>WebOrders</relationshipLabel>
    <relationshipName>WebOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WebOrder__c/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <description>Stage Oportunity field</description>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecting</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Needs Analysis</fullName>
            </value>
            <value>
                <fullName>Value Proposition</fullName>
            </value>
            <value>
                <fullName>Id. Decision Makers</fullName>
            </value>
            <value>
                <fullName>Perception Analysis</fullName>
            </value>
            <value>
                <fullName>Proposal/Price Quote</fullName>
            </value>
            <value>
                <fullName>Negotiation/Review</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/opportunityAndWebOrderActionTriggerTests.cls
@isTest
public with sharing class opportunityAndWebOrderActionTriggerTests {
    @isTest static void createFewOpportunityDeleteFewWebOrderTest() {
        List<Opportunity> newOpportunityList = new List<Opportunity>();

        for(Integer opportunityCount = 0; opportunityCount < 3; opportunityCount++) {
        newOpportunityList.Add(new Opportunity(Name = 'deleteFewOpportunityTest' + opportunityCount, 
                                                CloseDate = System.today(), 
                                                StageName = 'Prospecting'));
        }

        Test.startTest();
        Database.insert(newOpportunityList, false);
        Set<Id> opportunityIdSet = new Map<Id, Opportunity>(newOpportunityList).keySet();
        List<WebOrder__c> webOrdersList = [SELECT Id, Name FROM WebOrder__c WHERE OpportunityId__c IN :opportunityIdSet];
        List<Database.DeleteResult> deleteResultList = Database.delete(webOrdersList, false);

        List<Opportunity> opportunitiesList = [SELECT Id, Name FROM Opportunity WHERE Id IN :opportunityIdSet];
        List<WebOrder__c> deletedWebOrdersList = [SELECT Id, Name FROM WebOrder__c WHERE OpportunityId__c IN :opportunityIdSet];
        Test.stopTest();

        for(Database.DeleteResult result : deleteResultList) {
            System.assert(result.isSuccess());
        }
        System.assertEquals(0, opportunitiesList.size());
        System.assertEquals(0, deletedWebOrdersList.size());
    }

    @isTest static void createOpportunityDeleteWebOrderTest() {
        Opportunity newOpportunity = new Opportunity(Name = 'deleteOpportunityTest', 
                                                        CloseDate = System.today(), 
                                                        StageName = 'Prospecting');

        Test.startTest();
        Database.insert(newOpportunity, false);
        List<WebOrder__c> webOrdersList = [SELECT Id, Name FROM WebOrder__c WHERE OpportunityId__c = :newOpportunity.Id];
        List<Database.DeleteResult> deleteResult = Database.delete(webOrdersList, false);

        List<Opportunity> opportunitiesList = [SELECT Id, Name FROM Opportunity WHERE Id = :newOpportunity.Id];
        List<WebOrder__c> deletedWebOrdersList = [SELECT Id, Name FROM WebOrder__c WHERE OpportunityId__c = :newOpportunity.Id];
        Test.stopTest();
        
        System.assertEquals(1, deleteResult.size());
        System.assert(deleteResult[0].isSuccess());
        System.assertEquals(0, opportunitiesList.size());
        System.assertEquals(0, deletedWebOrdersList.size());
    }

    @isTest static void createFewWebOrderDeleteFewOpportunityTest() {
        List<WebOrder__c> newWebOrderList = new List<WebOrder__c>();

        for(Integer webOrderCount = 0; webOrderCount < 3; webOrderCount++) {
        newWebOrderList.Add(new WebOrder__c(Name = 'createFewWebOrderDeleteFewOpportunityTest' + webOrderCount, 
                                                CloseDate__c = System.today(), 
                                                StageName__c = 'Prospecting'));
        }

        Test.startTest();
        Database.insert(newWebOrderList, false);
        Set<Id> webOrderIdSet = new Map<Id, WebOrder__c>(newWebOrderList).keySet();
        List<Opportunity> opportunityList = [SELECT Id, Name FROM Opportunity WHERE WebOrderId__c IN :webOrderIdSet];
        List<Database.DeleteResult> deleteResultList = Database.delete(opportunityList, false);

        List<Opportunity> opportunitiesList = [SELECT Id, Name FROM Opportunity WHERE WebOrderId__c IN :webOrderIdSet];
        List<WebOrder__c> deletedWebOrdersList = [SELECT Id, Name FROM WebOrder__c WHERE Id IN :webOrderIdSet];
        Test.stopTest();

        for(Database.DeleteResult result : deleteResultList) {
            System.assert(result.isSuccess());
        }
        System.assertEquals(0, opportunitiesList.size());
        System.assertEquals(0, deletedWebOrdersList.size());
    }

    @isTest static void createWebOrderDeleteOpportunityTest() {
        WebOrder__c newWebOrder = new WebOrder__c(Name = 'createWebOrderDeleteOpportunityTest', 
                                                        CloseDate__c = System.today(), 
                                                        StageName__c = 'Prospecting');

        Test.startTest();
        Database.insert(newWebOrder, false);
        List<Opportunity> opportunityList = [SELECT Id, Name FROM Opportunity WHERE WebOrderId__c = :newWebOrder.Id];
        List<Database.DeleteResult> deleteResult = Database.delete(opportunityList, false);

        List<Opportunity> opportunitiesList = [SELECT Id, Name FROM Opportunity WHERE WebOrderId__c = :newWebOrder.Id];
        List<WebOrder__c> deletedWebOrdersList = [SELECT Id, Name FROM WebOrder__c WHERE Id = :newWebOrder.Id];
        Test.stopTest();
        
        System.assertEquals(1, deleteResult.size());
        System.assert(deleteResult[0].isSuccess());
        System.assertEquals(0, opportunitiesList.size());
        System.assertEquals(0, deletedWebOrdersList.size());
    }
}